/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as RegrasRouteImport } from './routes/regras'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as NaMidiaRouteImport } from './routes/na-midia'
import { Route as MinhaReservaRouteImport } from './routes/minha-reserva'
import { Route as ExpedicoesRouteImport } from './routes/expedicoes'
import { Route as DatasRouteImport } from './routes/datas'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservaSlugRouteImport } from './routes/reserva.$slug'
import { Route as MarcasElasNaSelaRouteImport } from './routes/marcas.elas-na-sela'
import { Route as MarcasCavalgadasRouteImport } from './routes/marcas.cavalgadas'
import { Route as MarcasCanastraACavaloRouteImport } from './routes/marcas.canastra-a-cavalo'
import { Route as ExpedicoesSlugRouteImport } from './routes/expedicoes.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAuthenticatedRouteImport } from './routes/admin._authenticated'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegrasRoute = RegrasRouteImport.update({
  id: '/regras',
  path: '/regras',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const NaMidiaRoute = NaMidiaRouteImport.update({
  id: '/na-midia',
  path: '/na-midia',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaReservaRoute = MinhaReservaRouteImport.update({
  id: '/minha-reserva',
  path: '/minha-reserva',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedicoesRoute = ExpedicoesRouteImport.update({
  id: '/expedicoes',
  path: '/expedicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasRoute = DatasRouteImport.update({
  id: '/datas',
  path: '/datas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservaSlugRoute = ReservaSlugRouteImport.update({
  id: '/reserva/$slug',
  path: '/reserva/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasElasNaSelaRoute = MarcasElasNaSelaRouteImport.update({
  id: '/marcas/elas-na-sela',
  path: '/marcas/elas-na-sela',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasCavalgadasRoute = MarcasCavalgadasRouteImport.update({
  id: '/marcas/cavalgadas',
  path: '/marcas/cavalgadas',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasCanastraACavaloRoute = MarcasCanastraACavaloRouteImport.update({
  id: '/marcas/canastra-a-cavalo',
  path: '/marcas/canastra-a-cavalo',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedicoesSlugRoute = ExpedicoesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExpedicoesRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedRoute = AdminAuthenticatedRouteImport.update({
  id: '/admin/_authenticated',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/datas': typeof DatasRoute
  '/expedicoes': typeof ExpedicoesRouteWithChildren
  '/minha-reserva': typeof MinhaReservaRoute
  '/na-midia': typeof NaMidiaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/regras': typeof RegrasRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AdminAuthenticatedRoute
  '/admin/login': typeof AdminLoginRoute
  '/expedicoes/$slug': typeof ExpedicoesSlugRoute
  '/marcas/canastra-a-cavalo': typeof MarcasCanastraACavaloRoute
  '/marcas/cavalgadas': typeof MarcasCavalgadasRoute
  '/marcas/elas-na-sela': typeof MarcasElasNaSelaRoute
  '/reserva/$slug': typeof ReservaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/datas': typeof DatasRoute
  '/expedicoes': typeof ExpedicoesRouteWithChildren
  '/minha-reserva': typeof MinhaReservaRoute
  '/na-midia': typeof NaMidiaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/regras': typeof RegrasRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AdminAuthenticatedRoute
  '/admin/login': typeof AdminLoginRoute
  '/expedicoes/$slug': typeof ExpedicoesSlugRoute
  '/marcas/canastra-a-cavalo': typeof MarcasCanastraACavaloRoute
  '/marcas/cavalgadas': typeof MarcasCavalgadasRoute
  '/marcas/elas-na-sela': typeof MarcasElasNaSelaRoute
  '/reserva/$slug': typeof ReservaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/datas': typeof DatasRoute
  '/expedicoes': typeof ExpedicoesRouteWithChildren
  '/minha-reserva': typeof MinhaReservaRoute
  '/na-midia': typeof NaMidiaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/regras': typeof RegrasRoute
  '/termos': typeof TermosRoute
  '/admin/_authenticated': typeof AdminAuthenticatedRoute
  '/admin/login': typeof AdminLoginRoute
  '/expedicoes/$slug': typeof ExpedicoesSlugRoute
  '/marcas/canastra-a-cavalo': typeof MarcasCanastraACavaloRoute
  '/marcas/cavalgadas': typeof MarcasCavalgadasRoute
  '/marcas/elas-na-sela': typeof MarcasElasNaSelaRoute
  '/reserva/$slug': typeof ReservaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/datas'
    | '/expedicoes'
    | '/minha-reserva'
    | '/na-midia'
    | '/privacidade'
    | '/quem-somos'
    | '/regras'
    | '/termos'
    | '/admin'
    | '/admin/login'
    | '/expedicoes/$slug'
    | '/marcas/canastra-a-cavalo'
    | '/marcas/cavalgadas'
    | '/marcas/elas-na-sela'
    | '/reserva/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/datas'
    | '/expedicoes'
    | '/minha-reserva'
    | '/na-midia'
    | '/privacidade'
    | '/quem-somos'
    | '/regras'
    | '/termos'
    | '/admin'
    | '/admin/login'
    | '/expedicoes/$slug'
    | '/marcas/canastra-a-cavalo'
    | '/marcas/cavalgadas'
    | '/marcas/elas-na-sela'
    | '/reserva/$slug'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/datas'
    | '/expedicoes'
    | '/minha-reserva'
    | '/na-midia'
    | '/privacidade'
    | '/quem-somos'
    | '/regras'
    | '/termos'
    | '/admin/_authenticated'
    | '/admin/login'
    | '/expedicoes/$slug'
    | '/marcas/canastra-a-cavalo'
    | '/marcas/cavalgadas'
    | '/marcas/elas-na-sela'
    | '/reserva/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  DatasRoute: typeof DatasRoute
  ExpedicoesRoute: typeof ExpedicoesRouteWithChildren
  MinhaReservaRoute: typeof MinhaReservaRoute
  NaMidiaRoute: typeof NaMidiaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  QuemSomosRoute: typeof QuemSomosRoute
  RegrasRoute: typeof RegrasRoute
  TermosRoute: typeof TermosRoute
  AdminAuthenticatedRoute: typeof AdminAuthenticatedRoute
  AdminLoginRoute: typeof AdminLoginRoute
  MarcasCanastraACavaloRoute: typeof MarcasCanastraACavaloRoute
  MarcasCavalgadasRoute: typeof MarcasCavalgadasRoute
  MarcasElasNaSelaRoute: typeof MarcasElasNaSelaRoute
  ReservaSlugRoute: typeof ReservaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regras': {
      id: '/regras'
      path: '/regras'
      fullPath: '/regras'
      preLoaderRoute: typeof RegrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/na-midia': {
      id: '/na-midia'
      path: '/na-midia'
      fullPath: '/na-midia'
      preLoaderRoute: typeof NaMidiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-reserva': {
      id: '/minha-reserva'
      path: '/minha-reserva'
      fullPath: '/minha-reserva'
      preLoaderRoute: typeof MinhaReservaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedicoes': {
      id: '/expedicoes'
      path: '/expedicoes'
      fullPath: '/expedicoes'
      preLoaderRoute: typeof ExpedicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datas': {
      id: '/datas'
      path: '/datas'
      fullPath: '/datas'
      preLoaderRoute: typeof DatasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserva/$slug': {
      id: '/reserva/$slug'
      path: '/reserva/$slug'
      fullPath: '/reserva/$slug'
      preLoaderRoute: typeof ReservaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas/elas-na-sela': {
      id: '/marcas/elas-na-sela'
      path: '/marcas/elas-na-sela'
      fullPath: '/marcas/elas-na-sela'
      preLoaderRoute: typeof MarcasElasNaSelaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas/cavalgadas': {
      id: '/marcas/cavalgadas'
      path: '/marcas/cavalgadas'
      fullPath: '/marcas/cavalgadas'
      preLoaderRoute: typeof MarcasCavalgadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas/canastra-a-cavalo': {
      id: '/marcas/canastra-a-cavalo'
      path: '/marcas/canastra-a-cavalo'
      fullPath: '/marcas/canastra-a-cavalo'
      preLoaderRoute: typeof MarcasCanastraACavaloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedicoes/$slug': {
      id: '/expedicoes/$slug'
      path: '/$slug'
      fullPath: '/expedicoes/$slug'
      preLoaderRoute: typeof ExpedicoesSlugRouteImport
      parentRoute: typeof ExpedicoesRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated': {
      id: '/admin/_authenticated'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExpedicoesRouteChildren {
  ExpedicoesSlugRoute: typeof ExpedicoesSlugRoute
}

const ExpedicoesRouteChildren: ExpedicoesRouteChildren = {
  ExpedicoesSlugRoute: ExpedicoesSlugRoute,
}

const ExpedicoesRouteWithChildren = ExpedicoesRoute._addFileChildren(
  ExpedicoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  DatasRoute: DatasRoute,
  ExpedicoesRoute: ExpedicoesRouteWithChildren,
  MinhaReservaRoute: MinhaReservaRoute,
  NaMidiaRoute: NaMidiaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  QuemSomosRoute: QuemSomosRoute,
  RegrasRoute: RegrasRoute,
  TermosRoute: TermosRoute,
  AdminAuthenticatedRoute: AdminAuthenticatedRoute,
  AdminLoginRoute: AdminLoginRoute,
  MarcasCanastraACavaloRoute: MarcasCanastraACavaloRoute,
  MarcasCavalgadasRoute: MarcasCavalgadasRoute,
  MarcasElasNaSelaRoute: MarcasElasNaSelaRoute,
  ReservaSlugRoute: ReservaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
