/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MinhaReservaRouteImport } from './routes/minha-reserva'
import { Route as ExpedicoesRouteImport } from './routes/expedicoes'
import { Route as DatasRouteImport } from './routes/datas'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservaSlugRouteImport } from './routes/reserva.$slug'
import { Route as MarcasElasNaSelaRouteImport } from './routes/marcas.elas-na-sela'
import { Route as MarcasCavalgadasRouteImport } from './routes/marcas.cavalgadas'
import { Route as MarcasCanastraACavaloRouteImport } from './routes/marcas.canastra-a-cavalo'
import { Route as ExpedicoesSlugRouteImport } from './routes/expedicoes.$slug'

const MinhaReservaRoute = MinhaReservaRouteImport.update({
  id: '/minha-reserva',
  path: '/minha-reserva',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedicoesRoute = ExpedicoesRouteImport.update({
  id: '/expedicoes',
  path: '/expedicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasRoute = DatasRouteImport.update({
  id: '/datas',
  path: '/datas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservaSlugRoute = ReservaSlugRouteImport.update({
  id: '/reserva/$slug',
  path: '/reserva/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasElasNaSelaRoute = MarcasElasNaSelaRouteImport.update({
  id: '/marcas/elas-na-sela',
  path: '/marcas/elas-na-sela',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasCavalgadasRoute = MarcasCavalgadasRouteImport.update({
  id: '/marcas/cavalgadas',
  path: '/marcas/cavalgadas',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasCanastraACavaloRoute = MarcasCanastraACavaloRouteImport.update({
  id: '/marcas/canastra-a-cavalo',
  path: '/marcas/canastra-a-cavalo',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedicoesSlugRoute = ExpedicoesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExpedicoesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/datas': typeof DatasRoute
  '/expedicoes': typeof ExpedicoesRouteWithChildren
  '/minha-reserva': typeof MinhaReservaRoute
  '/expedicoes/$slug': typeof ExpedicoesSlugRoute
  '/marcas/canastra-a-cavalo': typeof MarcasCanastraACavaloRoute
  '/marcas/cavalgadas': typeof MarcasCavalgadasRoute
  '/marcas/elas-na-sela': typeof MarcasElasNaSelaRoute
  '/reserva/$slug': typeof ReservaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/datas': typeof DatasRoute
  '/expedicoes': typeof ExpedicoesRouteWithChildren
  '/minha-reserva': typeof MinhaReservaRoute
  '/expedicoes/$slug': typeof ExpedicoesSlugRoute
  '/marcas/canastra-a-cavalo': typeof MarcasCanastraACavaloRoute
  '/marcas/cavalgadas': typeof MarcasCavalgadasRoute
  '/marcas/elas-na-sela': typeof MarcasElasNaSelaRoute
  '/reserva/$slug': typeof ReservaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/datas': typeof DatasRoute
  '/expedicoes': typeof ExpedicoesRouteWithChildren
  '/minha-reserva': typeof MinhaReservaRoute
  '/expedicoes/$slug': typeof ExpedicoesSlugRoute
  '/marcas/canastra-a-cavalo': typeof MarcasCanastraACavaloRoute
  '/marcas/cavalgadas': typeof MarcasCavalgadasRoute
  '/marcas/elas-na-sela': typeof MarcasElasNaSelaRoute
  '/reserva/$slug': typeof ReservaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/datas'
    | '/expedicoes'
    | '/minha-reserva'
    | '/expedicoes/$slug'
    | '/marcas/canastra-a-cavalo'
    | '/marcas/cavalgadas'
    | '/marcas/elas-na-sela'
    | '/reserva/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/datas'
    | '/expedicoes'
    | '/minha-reserva'
    | '/expedicoes/$slug'
    | '/marcas/canastra-a-cavalo'
    | '/marcas/cavalgadas'
    | '/marcas/elas-na-sela'
    | '/reserva/$slug'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/datas'
    | '/expedicoes'
    | '/minha-reserva'
    | '/expedicoes/$slug'
    | '/marcas/canastra-a-cavalo'
    | '/marcas/cavalgadas'
    | '/marcas/elas-na-sela'
    | '/reserva/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  DatasRoute: typeof DatasRoute
  ExpedicoesRoute: typeof ExpedicoesRouteWithChildren
  MinhaReservaRoute: typeof MinhaReservaRoute
  MarcasCanastraACavaloRoute: typeof MarcasCanastraACavaloRoute
  MarcasCavalgadasRoute: typeof MarcasCavalgadasRoute
  MarcasElasNaSelaRoute: typeof MarcasElasNaSelaRoute
  ReservaSlugRoute: typeof ReservaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/minha-reserva': {
      id: '/minha-reserva'
      path: '/minha-reserva'
      fullPath: '/minha-reserva'
      preLoaderRoute: typeof MinhaReservaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedicoes': {
      id: '/expedicoes'
      path: '/expedicoes'
      fullPath: '/expedicoes'
      preLoaderRoute: typeof ExpedicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datas': {
      id: '/datas'
      path: '/datas'
      fullPath: '/datas'
      preLoaderRoute: typeof DatasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserva/$slug': {
      id: '/reserva/$slug'
      path: '/reserva/$slug'
      fullPath: '/reserva/$slug'
      preLoaderRoute: typeof ReservaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas/elas-na-sela': {
      id: '/marcas/elas-na-sela'
      path: '/marcas/elas-na-sela'
      fullPath: '/marcas/elas-na-sela'
      preLoaderRoute: typeof MarcasElasNaSelaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas/cavalgadas': {
      id: '/marcas/cavalgadas'
      path: '/marcas/cavalgadas'
      fullPath: '/marcas/cavalgadas'
      preLoaderRoute: typeof MarcasCavalgadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas/canastra-a-cavalo': {
      id: '/marcas/canastra-a-cavalo'
      path: '/marcas/canastra-a-cavalo'
      fullPath: '/marcas/canastra-a-cavalo'
      preLoaderRoute: typeof MarcasCanastraACavaloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedicoes/$slug': {
      id: '/expedicoes/$slug'
      path: '/$slug'
      fullPath: '/expedicoes/$slug'
      preLoaderRoute: typeof ExpedicoesSlugRouteImport
      parentRoute: typeof ExpedicoesRoute
    }
  }
}

interface ExpedicoesRouteChildren {
  ExpedicoesSlugRoute: typeof ExpedicoesSlugRoute
}

const ExpedicoesRouteChildren: ExpedicoesRouteChildren = {
  ExpedicoesSlugRoute: ExpedicoesSlugRoute,
}

const ExpedicoesRouteWithChildren = ExpedicoesRoute._addFileChildren(
  ExpedicoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  DatasRoute: DatasRoute,
  ExpedicoesRoute: ExpedicoesRouteWithChildren,
  MinhaReservaRoute: MinhaReservaRoute,
  MarcasCanastraACavaloRoute: MarcasCanastraACavaloRoute,
  MarcasCavalgadasRoute: MarcasCavalgadasRoute,
  MarcasElasNaSelaRoute: MarcasElasNaSelaRoute,
  ReservaSlugRoute: ReservaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
