CREATE TABLE IF NOT EXISTS public.ia_contexto_logs (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id           uuid,
  reserva_id        uuid,
  participante_id   uuid,
  tipo              text,
  origem            text NOT NULL DEFAULT 's2s',
  telefone_hash     text,
  encontrado        boolean,
  tempo_execucao_ms integer,
  tamanho_payload   integer,
  sucesso           boolean NOT NULL DEFAULT false,
  erro              text,
  created_at        timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.ia_contexto_logs TO authenticated;
GRANT ALL    ON public.ia_contexto_logs TO service_role;

ALTER TABLE public.ia_contexto_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Internos leem contexto logs"
  ON public.ia_contexto_logs FOR SELECT
  TO authenticated
  USING (public.is_internal_user(auth.uid()));

CREATE INDEX IF NOT EXISTS idx_ia_contexto_logs_created ON public.ia_contexto_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ia_contexto_logs_lead    ON public.ia_contexto_logs (lead_id, created_at DESC);